apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: logcli
spec:
  version: v2.8.2
  homepage: https://github.com/grafana/loki
  caveats: |
    This plugin needs config LOKI_ADDR environment variable which points to a local instance directly
  shortDescription: LogCLI provides a command-line interface for querying logs against Loki.
  description: |
    LogCLI is the command-line interface to Grafana Loki.
    It facilitates running LogQL queries against a Loki instance.
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/grafana/loki/releases/download/v2.8.2/logcli-linux-amd64.zip
    sha256: 5aa8a83c343c68f9dcb63305642522391fa671abf1c74195feb855ab576e2904
    bin: logcli-linux-amd64
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/grafana/loki/releases/download/v2.8.2/logcli-darwin-arm64.zip
    sha256: bb3331e3d2b4a4925565d0f66ce579bdd4e6d183808444bf05afea2f1b814641
    bin: logcli-darwin-arm64
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/grafana/loki/releases/download/v2.8.2/logcli-windows-amd64.exe.zip
    sha256: fa900e4d9b77bf5f349cefdadadd4ad921d940dd58d4c74befcba07a133bdf11
    bin: logcli-windows-amd64.exe